/// <reference path="sst-env.d.ts" />

import 'sst';

/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module 'sst' {
  export interface Resource {
    Api: {
      name: string;
      type: 'sst.aws.Function';
      url: string;
    };
    Client: {
      type: 'sst.aws.StaticSite';
      url: string;
    };
    CorsAllowedOrigins: {
      type: 'sst.sst.Secret';
      value: string;
    };
    DbHostname: {
      type: 'sst.sst.Secret';
      value: string;
    };
    DbName: {
      type: 'sst.sst.Secret';
      value: string;
    };
    DbPassword: {
      type: 'sst.sst.Secret';
      value: string;
    };
    DbPort: {
      type: 'sst.sst.Secret';
      value: string;
    };
    DbUsername: {
      type: 'sst.sst.Secret';
      value: string;
    };
    EmailPassword: {
      type: 'sst.sst.Secret';
      value: string;
    };
    EmailUsername: {
      type: 'sst.sst.Secret';
      value: string;
    };
    FirebaseAdminSdkJson: {
      type: 'sst.sst.Secret';
      value: string;
    };
    FirebaseApiKey: {
      type: 'sst.sst.Secret';
      value: string;
    };
    FirebaseAppId: {
      type: 'sst.sst.Secret';
      value: string;
    };
    FirebaseAuthDomain: {
      type: 'sst.sst.Secret';
      value: string;
    };
    FirebaseMeasurementId: {
      type: 'sst.sst.Secret';
      value: string;
    };
    FirebaseMessagingSenderId: {
      type: 'sst.sst.Secret';
      value: string;
    };
    FirebaseProjectId: {
      type: 'sst.sst.Secret';
      value: string;
    };
    FirebaseStorageBucket: {
      type: 'sst.sst.Secret';
      value: string;
    };
    MediaBucket: {
      name: string;
      type: 'sst.aws.Bucket';
    };
    YoutubeApiKey: {
      type: 'sst.sst.Secret';
      value: string;
    };
  }
}

export {};
